### ISSUE TITLE
mailoney, list index out of range

### ISSUE THREAD

**Issue by t3chn0m4g3** [vorband/ewsposter#10]
On a running T-Pot 18.10 (dev) `ewsposter` crashes when reading mailoney logs:
```
 => Starting MAILONEY Modul.
 => Send Limit is set to : 500. Adapting to limit!
Traceback (most recent call last):
  File "/opt/ewsposter/ews.py", line 2425, in <module>
    eval(i+'()')
  File "<string>", line 1, in <module>
  File "/opt/ewsposter/ews.py", line 2009, in mailoney
    if not any(s in line.split(" ")[1] for s in trigger):
  File "/opt/ewsposter/ews.py", line 2009, in <genexpr>
    if not any(s in line.split(" ")[1] for s in trigger):
IndexError: list index out of range
```

This is the log to reproduce the error:
```
[1530090631.61][37.49.224.247:51739]
[1530090631.61][37.49.224.247:51739] **************************************************
[1530090631.61][37.49.224.247:51739] Mail from: spameri@tiscali.it
[1530090631.61][37.49.224.247:51739] Mail to: spameri@tiscali.it
[1530090631.61][37.49.224.247:51739] Data:
[1530090631.61][37.49.224.247:51739] From: spameri@tiscali.it\nSubject: 84.154.44.210\nTo: spameri@tiscali.it\nDate: Wed, 27 Jun 2018 02:10:31 -0700\nX-Priority: 3\nX-Library: Indy 8.0.25\n\nt_Smtp.LocalIP
[1530100705.4][1.164.207.229:4203]
[1530100705.4][1.164.207.229:4203] **************************************************
[1530100705.4][1.164.207.229:4203] Mail from: z2007tw@yahoo.com.tw
[1530100705.4][1.164.207.229:4203] Mail to: vxxj.zhge@msa.hinet.net
[1530100705.4][1.164.207.229:4203] Data:
[1530100705.4][1.164.207.229:4203] Received: from  ([45.113.241.229])\n\tby 84.154.44.210;\n\tWed, 27 Jun 2018 17:54:23 +0600\nMessage-ID: <73e8qa652mi-9$5ru0@edo7.imx>\nFrom: "" <z2007tw@yahoo.com.tw>\nTo: <vxxj.zhge@msa.hinet.net>\nSubject: BC_84.154.44.210\nDate: Wed, 27 Jun 18 17:54:23 GMT\nMIME-Version: 1.0\nContent-Type: multipart/alternative;\n\tboundary="----=_NextPart_000_000D_01C2CC60.49F4EC70"\n
[1530122977.54][37.49.224.247:56035]
[1530122977.54][37.49.224.247:56035] **************************************************
[1530122977.54][37.49.224.247:56035] Mail from: info@marcellus.com
[1530122977.54][37.49.224.247:56035] Mail to: barristerwilliams111@gmail.com, imf.home@hotmail.com, kelvin_kiwizzy@yahoo.com
[1530122977.54][37.49.224.247:56035] Data:
[1530122977.54][37.49.224.247:56035] Reply-To: <statedepartment1@yahoo.com>\nFrom: "Mr Roland de Marcellus"<info@marcellus.com>\nSubject: U.S DEPARTMENT OF STATE.      84.154.44.210\nDate: Wed, 27 Jun 2018 11:09:34 -0700\nMIME-Version: 1.0\nContent-Type: text/html;\n\tcharset="Windows-1251"\nContent-Transfer-Encoding: 7bit\nX-Priority: 3\nX-MSMail-Priority: Normal\nX-Mailer: Microsoft Outlook Express 6.00.2600.0000\nX-MimeOLE: Produced By Microsoft MimeOLE V6.00.2600.0000\n\n<HTML><HEAD><TITLE></TITLE>\n</HEAD>\n<BODY bgcolor=#FFFFFF leftmargin=5 topmargin=5 rightmargin=5 bottommargin=5>\n<FONT size=2 color=#000000 face="Arial">\n<DIV>\n<B>U.S Department of State</B></DIV>\n<DIV>\n<B>2201 C Street NW</B></DIV>\n<DIV>\n<B>Washington, DC 20520.</B></DIV>\n<DIV>\n<B> </B></DIV>\n<DIV>\n<B>&nbsp;</B></DIV>\n<DIV>\n<B>Dear Beneficiary</B></DIV>\n<DIV>\n<B> </B></DIV>\n<DIV>\n<B>&nbsp;</B></DIV>\n<DIV>\n<B>Your ATM Visa Card will be shipped through USPS to your Address. I am Mr Roland de Marcellus, Acting Deputy Assistant Secretary of State for International Finance &amp; Development (BUREAU OF ECONOMIC AND BUSINESS AFFAIRS). This is to inform you officially that after our investigations with the Federal Bureau of Investigation (FBI), Central Intelligence Agency (CIA) and other Security Agencies in the Country for the year 2017 and 2018, we discovered that you have not yet received your over due fund.</B></DIV>\n<DIV>\n<B> </B></DIV>\n<DIV>\n<B>&nbsp;</B></DIV>\n<DIV>\n<B>I have made it my first point of call since taking office to settle all Outstanding Payments accrued to Individuals or Corporations with respect to local and overseas contract payment, Debt Rescheduling and Outstanding Compensation payment.</B></DIV>\n<DIV>\n<B> </B></DIV>\n<DIV>\n<B>&nbsp;</B></DIV>\n<DIV>\n<B>This is to make sure all Outstanding payments are settled this fiscal year 2018. On Behalf of the entire staff of the U.S. Department of State and the United Nations in collaboration with World Bank, we apologize for the delay of your contract payment, Winning or Inheritance funds from most of African Countries and all the inconveniences you encountered while pursuing this payment. However, from the records of outstanding beneficiaries due for payment with the U.S Secretary of State, your name was discovered as next on the list of beneficiaries who has not yet received their payments.</B></DIV>\n<DIV>\n<B> </B></DIV>\n<DIV>\n<B>&nbsp;</B></DIV>\n<DIV>\n<B>I have your file here in my office and it says that you are yet to receive your funds valued at US$1,850,000.00 (One Million, Eight Hundred And Fifty Thousand United States Dollars). This Funds will now be delivered to your designated address on your preferred payment option. We have perfected all modules on how to bring this fund to your designated address without any problem, but be aware that the United Nations and the United States Government has only authorized my office to release the Sum of US$1,850,000.00 to you as true beneficiary of the Funds.</B></DIV>\n<DIV>\n<B> </B></DIV>\n<DIV>\n<B>&nbsp;</B></DIV>\n<DIV>\n<B>Note that your loaded ATM Visa Card will be mailed to you through Priority Mail Express (USPS) to your designated address immediately you admit full compliance to this email. Due to my busy schedules you are advised to kindly get in contact with our correspondent Mr Mark Christopher with the below details enclosed to help ensure safe mailing of your ATM Visa Card:</B></DIV>\n<DIV>\n<B> </B></DIV>\n<DIV>\n<B>&nbsp;</B></DIV>\n<DIV>\n<B>Your Full Name:</B></DIV>\n<DIV>\n<B>Your Contact House Address:</B></DIV>\n<DIV>\n<B>Name of City of Residence:</B></DIV>\n<DIV>\n<B>Country of Residence:</B></DIV>\n<DIV>\n<B>Direct Mobile Telephone Number:</B></DIV>\n<DIV>\n<B>ID Card, DL or Passport Copy:</B></DIV>\n<DIV>\n<B>Age and Occupation:</B></DIV>\n<DIV>\n<B> </B></DIV>\n<DIV>\n<B>&nbsp;</B></DIV>\n<DIV>\n<B>Contact Mr Mark Christopher immediately by emailing the address below:</B></DIV>\n<DIV>\n<B> </B></DIV>\n<DIV>\n<B>&nbsp;</B></DIV>\n<DIV>\n<B>Name: Mr Mark Christopher.</B></DIV>\n<DIV>\n<B>Email: statedepartment1@yahoo.com</B></DIV>\n<DIV>\n<B>Telephone: +1 (253) 215-4271</B></DIV>\n<DIV>\n<B> </B></DIV>\n<DIV>\n<B>&nbsp;</B></DIV>\n<DIV>\n<B>He is obliged to treat your case with utmost urgency as soon as you contact him and fill out your correct details including all reachable phone numbers for him to get in touch with you via phone and email.</B></DIV>\n<DIV>\n<B> </B></DIV>\n<DIV>\n<B>&nbsp;</B></DIV>\n<DIV>\n<B>NOTE: Every documentation proof for your fund have been packaged and sealed to be mailed together with your Visa Card to your address. Therefore, the only obligation required of you by the laws of the Government of United States and the financial Monetary Policy of the Supreme Court, states that; you as a beneficiary must officially obtain the irrevocable LEGAL STAY OF PROCEED from the Supreme Court of USA, as a means to justify the legitimacy, transparency and clean bill of funds from USA so that by the time your funds gets to you, no authority will question the funds as it has been legally certified free from all financial Malpractices and facets. The LEGAL STAY OF PROCEED is valued at a cost of ($550) please take note of that.</B></DIV>\n<DIV>\n<B> </B></DIV>\n<DIV>\n<B>&nbsp;</B></DIV>\n<DIV>\n<B>As soon as the above mentioned $550 is received, The LEGAL STAY OF PROCEED will be secured on your behalf immediately. I need all the compliance that I can get from you to ensure we get this project accomplished. Personally, I am very sorry for the delay you have gone through in the past years. Thanks for adhering to this instructions which are meant for your sole benefit, once again accept my congratulations in advance.</B></DIV>\n<DIV>\n<B> </B></DIV>\n<DIV>\n<B>&nbsp;</B></DIV>\n<DIV>\n<B>Thanks for your cooperation as your quick response to this email notice with adherence to the above instructions is highly anticipated.</B></DIV>\n<DIV>\n<B> </B></DIV>\n<DIV>\n<B>&nbsp;</B></DIV>\n<DIV>\n<B>Yours Sincerely,</B></DIV>\n<DIV>\n<B>&nbsp;</B></DIV>\n<DIV>\n<B>&nbsp;</B></DIV>\n<DIV>\n<B>Mr Roland de Marcellus.</B></DIV>\n</FONT>\n</BODY></HTML>
[1530298795.25][95.181.178.182:58950]
[1530298795.25][95.181.178.182:58950] **************************************************
[1530298795.25][95.181.178.182:58950] Mail from: smtp2001soho@yahoo.com
[1530298795.25][95.181.178.182:58950] Mail to: antispamguard@freemailhost.ru
[1530298795.25][95.181.178.182:58950] Data:
[1530298795.25][95.181.178.182:58950] Subject: 7534df112cn206:84.154.44.210<65.72.18.129>\nX-Priority: 1\nX-Mail-Priority: Highest\nContent-Type: text/plain;\n\n
```

Deleting the log results in resume of normal ewsposter operation.

**Comment by vorband** [comment]
The blank line causes the processing to fail. I can fix this after my vacation, but could it be you are using the wrong logfile? 
I believe the logfile expected is the one with the raw smtp commands. 
Cannot verify it from here though.

**Comment by t3chn0m4g3** [comment]
Thanks, I pasted the `mail.log`, but the log in question is `commands.log` which is configured to be used with ewsposter.

The error is caused by the whitespace following the `timestamp, src_ip, src_port` fields. Erasing the corresponding lines results in normal operation.

**Comment by vorband** [comment]
All right. Will be fixed as soon as

**Comment by vorband** [comment]
... I am back.

**Comment by vorband** [comment]
should now be fixed in https://github.com/vorband/ewsposter/commit/282d986ff09d1865fbd3de86d95b3201efcdd738

**Comment by vorband** [comment]
assuming this is fixed
