### ISSUE TITLE
EWSPoster crashes if glastopf.db is empty or corrupt

### ISSUE THREAD

**Issue by t3chn0m4g3** [vorband/ewsposter#2]
Ewsposter should continue working even if some log files are empty or unavailable.

Example for Dionaea:
```
EWS Poster v1.9 (c) by Markus Schroer <markus.schroer@telekom.de>
Traceback (most recent call last):
  File "/opt/ewsposter/ews.py", line 2087, in <module>

 => Create ews.idx counterfile
 => Create lock socket successfull.
 => Sender : No Jobs to send in /opt/ewsposter/spool/
 => Starting Glastopf V3.x Modul.
    => [GLASTOPFV3] [INFO] Sqlitedb /data/glastopf/db/glastopf.db is corrupt or does not contain events. Skipping ! 
 => Starting Dionaea Modul.
    eval(i+'()')
  File "<string>", line 1, in <module>
  File "/opt/ewsposter/ews.py", line 955, in dionaea
    c.execute("SELECT max(connection) from connections;")
sqlite3.OperationalError: no such table: connections
```

**Comment by vorband** [comment]
are you sure this issue still persists? 

It should have already been fixed here: ff4ee277089f7a296d62e1c94df77b7cad0eadec

**Comment by t3chn0m4g3** [comment]
yes, happened yesterday with latest [build](https://hub.docker.com/r/dtagdevsec/ewsposter/)

https://github.com/vorband/ewsposter/commit/ff4ee277089f7a296d62e1c94df77b7cad0eadec handles if the file is not available, however WRT to glastopf the file was available but empty.

Just deleted all log files and ewsposter seems to handle that as expected. thank you.
```
ewsposter    | EWS Poster v1.9 (c) by Markus Schroer <markus.schroer@telekom.de>
ewsposter    | 
ewsposter    |  => Create ews.idx counterfile
ewsposter    |  => Create lock socket successfull.
ewsposter    |  => Sender : No Jobs to send in /opt/ewsposter/spool/
ewsposter    |  => Starting Glastopf V3.x Modul.
ewsposter    |     => [GLASTOPFV3] [INFO] Missing sqlitedb file /data/glastopf/db/glastopf.db. Skipping !
ewsposter    |  => Starting Dionaea Modul.
ewsposter    |     => [DIONAEA] [ERROR] Missing sqlitedb file /data/dionaea/log/dionaea.sqlite. Abort !
ewsposter    |  => Starting Honeytrap Modul.
ewsposter    |     => [HONEYTRAP] [ERROR] Missing Attacker File /data/honeytrap/log/attacker.log. Abort !
ewsposter    |     -> Calculate MD5sum for Payload Files
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Starting eMobility Modul.
ewsposter    |     => [EMOBILITY] [ERROR] Missing LogFile /data/emobility/log/centralsystemEWS.log. Skip !
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Starting Conpot Modul.
ewsposter    |     => [CONPOT] [ERROR] Missing LogFile /data/conpot/log/conpot.json. Skip !
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Starting Cowrie Modul.
ewsposter    |     => [COWRIE] [ERROR] Missing LogFile /data/cowrie/log/cowrie.json. Skip !
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |  => Starting Elasticpot Modul.
ewsposter    |     => [ELASTICPOT] [ERROR] Missing LogFile /data/elasticpot/log/elasticpot.log. Skip !
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Starting Suricata Modul.
ewsposter    |     => [SURICATA] [ERROR] Missing LogFile /data/suricata/log/suricata_ews.log. Skip !
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Starting RDPY Modul.
ewsposter    |     => [RDPY] [ERROR] Missing LogFile /data/rdpy/log/rdpy.log. Skip !
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Starting MAILONEY Modul.
ewsposter    |     => [MAILONEY] [ERROR] Missing LogFile /data/mailoney/log/commands.log. Skip !
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Starting VNCLOWPOT Modul.
```

**Comment by t3chn0m4g3** [comment]
Adjusted the title, since it better reflects the fact that https://github.com/vorband/ewsposter/commit/ff4ee277089f7a296d62e1c94df77b7cad0eadec takes care of non-available log files while the crashes seem to be isolated to glastopf log module.

**Comment by vorband** [comment]
The error was in the Dionaea module, not in Glastopf., see error message. However, this has been fixed before. Cannot reproduce it after the fix. Testing with sqlitedb without connections showed that error is properly handled. 

In case it still persists, please share your sqlitedb. Thanks. :)

**Comment by t3chn0m4g3** [comment]
Confirmed...
```
 => Starting Dionaea Modul.
    => [DIONAEA] [INFO] Sqlitedb /data/dionaea/log/dionaea.sqlite is corrupt or does not contain events. Skipping ! 
```

Of course Dionaea... that's happening when working in parallel on Glastopf. Classic Freud'sche Fehlleistung.

Thank you.
