### ISSUE TITLE
Error WRT to Suricata Logs

### ISSUE THREAD

**Issue by t3chn0m4g3** [vorband/ewsposter#4]
ewsposter error message:
```
Traceback (most recent call last):
  File "/opt/ewsposter/ews.py", line 2087, in <module>
    eval(i+'()')
  File "<string>", line 1, in <module>
  File "/opt/ewsposter/ews.py", line 1682, in suricata
    "sport"     : "%d" % content["src_port"],
KeyError: 'src_port'
```
Log to reproduce:
[log_suri.txt](https://github.com/vorband/ewsposter/files/1947561/log_suri.txt)

**Comment by vorband** [comment]
done in db594864d56d0aee0e48116fcd0ebb14cbe0226a -  please test with fresh data as the test data did not contain alerts with src_port set (ICMP), then close issue.

**Comment by t3chn0m4g3** [comment]
LGTM - does not crash if `src_port` is not available.

```
{"timestamp":"2018-04-26T10:07:49.678475+0000","t-pot_ip_int":"172.20.254.120","t-pot_ip_ext":"87.150.238.182","host":"9351e6e58086","proto":"IPv6-ICMP","@version":"1","t-pot_hostname":"spottycathedral","icmp_code":0,"dest_ip":"ff02:0000:0000:0000:0000:0000:0000:0016","in_iface":"ens33","src_ip":"fe80:0000:0000:0000:08a9:2993:c2aa:4dc8","path":"/data/suricata/log/eve.json","alert":{"category":"Generic Protocol Command Decode","severity":3,"rev":2,"gid":1,"action":"allowed","signature_id":2200094,"signature":"SURICATA zero length padN option"},"tags":["_geoip_lookup_failure"],"icmp_type":143,"geoip":{},"event_type":"alert","payload_printable":"................","@timestamp":"2018-04-26T10:07:49.678Z","type":"Suricata","stream":0,"flow_id":1230742826080843}
{"timestamp":"2018-04-26T10:07:52.647884+0000","t-pot_ip_int":"172.20.254.120","t-pot_ip_ext":"87.150.238.182","host":"9351e6e58086","proto":"IPv6-ICMP","@version":"1","t-pot_hostname":"spottycathedral","icmp_code":0,"dest_ip":"ff02:0000:0000:0000:0000:0000:0000:0016","in_iface":"ens33","src_ip":"fe80:0000:0000:0000:08a9:2993:c2aa:4dc8","path":"/data/suricata/log/eve.json","alert":{"category":"Generic Protocol Command Decode","severity":3,"rev":2,"gid":1,"action":"allowed","signature_id":2200094,"signature":"SURICATA zero length padN option"},"tags":["_geoip_lookup_failure"],"icmp_type":143,"geoip":{},"event_type":"alert","payload_printable":"................","@timestamp":"2018-04-26T10:07:52.647Z","type":"Suricata","stream":0,"flow_id":1230742826080843}
{"timestamp":"2018-04-26T10:08:48.559748+0000","t-pot_ip_int":"172.20.254.120","t-pot_ip_ext":"87.150.238.182","host":"9351e6e58086","proto":"IPv6-ICMP","@version":"1","t-pot_hostname":"spottycathedral","icmp_code":0,"dest_ip":"ff02:0000:0000:0000:0000:0000:0000:0016","in_iface":"ens33","src_ip":"fe80:0000:0000:0000:1cf7:2fd2:9f6b:0e8c","path":"/data/suricata/log/eve.json","alert":{"category":"Generic Protocol Command Decode","severity":3,"rev":2,"gid":1,"action":"allowed","signature_id":2200094,"signature":"SURICATA zero length padN option"},"tags":["_geoip_lookup_failure"],"icmp_type":143,"geoip":{},"event_type":"alert","payload_printable":"................","@timestamp":"2018-04-26T10:08:48.559Z","type":"Suricata","stream":0,"flow_id":954310144854660}
{"timestamp":"2018-04-26T10:08:50.607025+0000","t-pot_ip_int":"172.20.254.120","t-pot_ip_ext":"87.150.238.182","host":"9351e6e58086","proto":"IPv6-ICMP","@version":"1","t-pot_hostname":"spottycathedral","icmp_code":0,"dest_ip":"ff02:0000:0000:0000:0000:0000:0000:0016","in_iface":"ens33","src_ip":"fe80:0000:0000:0000:1cf7:2fd2:9f6b:0e8c","path":"/data/suricata/log/eve.json","alert":{"category":"Generic Protocol Command Decode","severity":3,"rev":2,"gid":1,"action":"allowed","signature_id":2200094,"signature":"SURICATA zero length padN option"},"tags":["_geoip_lookup_failure"],"icmp_type":143,"geoip":{},"event_type":"alert","payload_printable":"................","@timestamp":"2018-04-26T10:08:50.607Z","type":"Suricata","stream":0,"flow_id":954310144854660}
{"timestamp":"2018-04-26T10:08:50.608269+0000","t-pot_ip_int":"172.20.254.120","t-pot_ip_ext":"87.150.238.182","host":"9351e6e58086","proto":"IPv6-ICMP","@version":"1","t-pot_hostname":"spottycathedral","icmp_code":0,"dest_ip":"ff02:0000:0000:0000:0000:0000:0000:0016","in_iface":"ens33","src_ip":"fe80:0000:0000:0000:08a9:2993:c2aa:4dc8","path":"/data/suricata/log/eve.json","alert":{"category":"Generic Protocol Command Decode","severity":3,"rev":2,"gid":1,"action":"allowed","signature_id":2200094,"signature":"SURICATA zero length padN option"},"tags":["_geoip_lookup_failure"],"icmp_type":143,"geoip":{},"event_type":"alert","payload_printable":"................","@timestamp":"2018-04-26T10:08:50.608Z","type":"Suricata","stream":0,"flow_id":1230742830073869}
{"timestamp":"2018-04-26T10:08:53.679004+0000","t-pot_ip_int":"172.20.254.120","t-pot_ip_ext":"87.150.238.182","host":"9351e6e58086","proto":"IPv6-ICMP","@version":"1","t-pot_hostname":"spottycathedral","icmp_code":0,"dest_ip":"ff02:0000:0000:0000:0000:0000:0000:0016","in_iface":"ens33","src_ip":"fe80:0000:0000:0000:08a9:2993:c2aa:4dc8","path":"/data/suricata/log/eve.json","alert":{"category":"Generic Protocol Command Decode","severity":3,"rev":2,"gid":1,"action":"allowed","signature_id":2200094,"signature":"SURICATA zero length padN option"},"tags":["_geoip_lookup_failure"],"icmp_type":143,"geoip":{},"event_type":"alert","payload_printable":"................","@timestamp":"2018-04-26T10:08:53.679Z","type":"Suricata","stream":0,"flow_id":1230742830073869}
```
